"""empty message

Revision ID: 1595a25b603b
Revises: 2d70b2b7f421
Create Date: 2017-01-07 15:40:55.337138

"""

# revision identifiers, used by Alembic.
revision = '1595a25b603b'
down_revision = '2d70b2b7f421'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('com_number', sa.String(), nullable=True))
    op.add_column('company', sa.Column('tax_number', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'tax_number')
    op.drop_column('company', 'com_number')
    ### end Alembic commands ###
