"""empty message

Revision ID: 197a41a715c0
Revises: None
Create Date: 2017-01-07 14:27:19.546690

"""

# revision identifiers, used by Alembic.
revision = '197a41a715c0'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('broker',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('date_add', sa.DateTime(), server_default=sa.text(u'now()'), nullable=True),
    sa.Column('date_upd', sa.DateTime(), server_default=sa.text(u'now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('com_number', sa.Integer(), nullable=True),
    sa.Column('tax_number', sa.Integer(), nullable=True),
    sa.Column('date_add', sa.DateTime(), server_default=sa.text(u'now()'), nullable=True),
    sa.Column('date_upd', sa.DateTime(), server_default=sa.text(u'now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('date_add', sa.DateTime(), server_default=sa.text(u'now()'), nullable=True),
    sa.Column('date_upd', sa.DateTime(), server_default=sa.text(u'now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('device_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_token', sa.String(), nullable=True),
    sa.Column('date_add', sa.DateTime(), server_default=sa.text(u'now()'), nullable=True),
    sa.Column('date_upd', sa.DateTime(), server_default=sa.text(u'now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('date_add', sa.DateTime(), server_default=sa.text(u'now()'), nullable=True),
    sa.Column('date_upd', sa.DateTime(), server_default=sa.text(u'now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('broker_credit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('broker_id', sa.Integer(), nullable=True),
    sa.Column('owner_name', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('ex_date', sa.DateTime(), nullable=True),
    sa.Column('csv', sa.Integer(), nullable=True),
    sa.Column('date_add', sa.DateTime(), server_default=sa.text(u'now()'), nullable=True),
    sa.Column('date_upd', sa.DateTime(), server_default=sa.text(u'now()'), nullable=True),
    sa.ForeignKeyConstraint(['broker_id'], ['broker.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('company_credit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('owner_name', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('ex_date', sa.DateTime(), nullable=True),
    sa.Column('csv', sa.Integer(), nullable=True),
    sa.Column('date_add', sa.DateTime(), server_default=sa.text(u'now()'), nullable=True),
    sa.Column('date_upd', sa.DateTime(), server_default=sa.text(u'now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer_credit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('owner_name', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('ex_date', sa.DateTime(), nullable=True),
    sa.Column('csv', sa.Integer(), nullable=True),
    sa.Column('date_add', sa.DateTime(), server_default=sa.text(u'now()'), nullable=True),
    sa.Column('date_upd', sa.DateTime(), server_default=sa.text(u'now()'), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('current_value', sa.Float(), nullable=True),
    sa.Column('last_value', sa.Float(), nullable=True),
    sa.Column('type', sa.Binary(), nullable=True),
    sa.Column('init_no', sa.Integer(), nullable=True),
    sa.Column('curr_no', sa.Integer(), nullable=True),
    sa.Column('date_add', sa.DateTime(), server_default=sa.text(u'now()'), nullable=True),
    sa.Column('date_upd', sa.DateTime(), server_default=sa.text(u'now()'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=True),
    sa.Column('broker_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('buy_value', sa.Float(), nullable=True),
    sa.Column('sell_value', sa.Float(), nullable=True),
    sa.Column('date_add', sa.DateTime(), server_default=sa.text(u'now()'), nullable=True),
    sa.Column('date_upd', sa.DateTime(), server_default=sa.text(u'now()'), nullable=True),
    sa.ForeignKeyConstraint(['broker_id'], ['broker.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['stock_id'], ['stock.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('broker_id', sa.Integer(), nullable=True),
    sa.Column('no_stocks', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=True),
    sa.Column('date_add', sa.DateTime(), server_default=sa.text(u'now()'), nullable=True),
    sa.Column('date_upd', sa.DateTime(), server_default=sa.text(u'now()'), nullable=True),
    sa.ForeignKeyConstraint(['broker_id'], ['broker.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['stock_id'], ['stock.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('request')
    op.drop_table('history')
    op.drop_table('stock')
    op.drop_table('customer_credit')
    op.drop_table('company_credit')
    op.drop_table('broker_credit')
    op.drop_table('orders')
    op.drop_table('device_token')
    op.drop_table('customer')
    op.drop_table('company')
    op.drop_table('broker')
    ### end Alembic commands ###
