"""empty message

Revision ID: 262d8584ae4a
Revises: 7fde35df162b
Create Date: 2017-01-07 15:45:39.345648

"""

# revision identifiers, used by Alembic.
revision = '262d8584ae4a'
down_revision = '7fde35df162b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock', sa.Column('type', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock', 'type')
    ### end Alembic commands ###
