"""empty message

Revision ID: 2d70b2b7f421
Revises: 91c04931b7d9
Create Date: 2017-01-07 15:40:46.326596

"""

# revision identifiers, used by Alembic.
revision = '2d70b2b7f421'
down_revision = '91c04931b7d9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'com_number')
    op.drop_column('company', 'tax_number')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('tax_number', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('company', sa.Column('com_number', sa.INTEGER(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
