"""empty message

Revision ID: 7fde35df162b
Revises: 1595a25b603b
Create Date: 2017-01-07 15:45:33.065704

"""

# revision identifiers, used by Alembic.
revision = '7fde35df162b'
down_revision = '1595a25b603b'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock', 'type')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock', sa.Column('type', postgresql.BYTEA(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
