"""empty message

Revision ID: 91c04931b7d9
Revises: 197a41a715c0
Create Date: 2017-01-07 15:33:34.814685

"""

# revision identifiers, used by Alembic.
revision = '91c04931b7d9'
down_revision = '197a41a715c0'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('date_add', sa.DateTime(), server_default=sa.text(u'now()'), nullable=True),
    sa.Column('date_upd', sa.DateTime(), server_default=sa.text(u'now()'), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['stock_id'], ['stock.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('date_add', sa.DateTime(), server_default=sa.text(u'now()'), nullable=True),
    sa.Column('date_upd', sa.DateTime(), server_default=sa.text(u'now()'), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['stock.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('orders')
    op.add_column(u'request', sa.Column('type', sa.Binary(), nullable=True))
    op.add_column(u'request', sa.Column('value_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'request', 'stock_values', ['value_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'request', type_='foreignkey')
    op.drop_column(u'request', 'value_id')
    op.drop_column(u'request', 'type')
    op.create_table('orders',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('stock_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('value', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('date_add', postgresql.TIMESTAMP(), server_default=sa.text(u'now()'), autoincrement=False, nullable=True),
    sa.Column('date_upd', postgresql.TIMESTAMP(), server_default=sa.text(u'now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=u'orders_pkey')
    )
    op.drop_table('stock_values')
    op.drop_table('customer_stocks')
    ### end Alembic commands ###
