"""empty message

Revision ID: d85fd30c1b3a
Revises: 262d8584ae4a
Create Date: 2017-01-07 15:55:26.504490

"""

# revision identifiers, used by Alembic.
revision = 'd85fd30c1b3a'
down_revision = '262d8584ae4a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock', 'type')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock', sa.Column('type', sa.INTEGER(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
