"""empty message

Revision ID: dd254f74c8b7
Revises: d85fd30c1b3a
Create Date: 2017-01-07 15:56:13.873694

"""

# revision identifiers, used by Alembic.
revision = 'dd254f74c8b7'
down_revision = 'd85fd30c1b3a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock', sa.Column('type', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stock', 'type')
    ### end Alembic commands ###
